"""
Export & delivery formats for PodcastGPT analyses.

Pure rendering of dicts → markdown/text/Telegram. No Streamlit
or session-state dependencies.
"""

import os
from datetime import datetime
from typing import Any, Dict, List, Optional

import requests

try:
    from weasyprint import HTML as WeasyprintHTML
    _WEASYPRINT_OK = True
except Exception:
    _WEASYPRINT_OK = False

from .insights import format_highlights


# ── Telegram ─────────────────────────────────────────────────────────────

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "8691576484")


def deliver_to_telegram(
    episode_title: str,
    result: Dict[str, Any],
    em_insights: Dict[str, Any],
    podcast_title: str = "",
    bot_token: Optional[str] = None,
    chat_id: Optional[str] = None,
) -> bool:
    """Send a compact analysis summary to Telegram. Returns True on success."""
    token = bot_token or TELEGRAM_BOT_TOKEN
    target = chat_id or TELEGRAM_CHAT_ID
    if not token:
        return False

    guest = result.get("podcast_guest", "Unknown")
    guest_org = result.get("podcast_guest_org", "")
    sentiment = em_insights.get("sentiment", "—")
    regions = ", ".join(em_insights.get("regions", [])[:3])
    themes = ", ".join(em_insights.get("themes", [])[:3])
    highlights = [
        h.strip().lstrip("•-* ")
        for h in result.get("podcast_highlights", "").split("\n")
        if h.strip()
    ][:4]
    bullet_pts = "\n".join(f"• {h}" for h in highlights) or "—"
    model_used = result.get("_model_used", "—")

    msg = (
        f"🎙️ *PodcastGPT — New Analysis*\n\n"
        f"*{episode_title}*\n"
        f"_{podcast_title}_\n\n"
        f"👤 *Guest:* {guest}{' | ' + guest_org if guest_org else ''}\n"
        f"📊 *Sentiment:* {sentiment}\n"
        f"🌍 *Regions:* {regions or '—'}\n"
        f"🎯 *Themes:* {themes or '—'}\n\n"
        f"*Key Takeaways:*\n{bullet_pts}\n\n"
        f"_Model: {model_used}_"
    )

    try:
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        resp = requests.post(
            url,
            json={"chat_id": target, "text": msg, "parse_mode": "Markdown"},
            timeout=10,
        )
        return resp.status_code == 200
    except Exception:
        return False


# ── Markdown / Text exports ──────────────────────────────────────────────

def generate_markdown_export(episode_title: str, result: Dict[str, Any]) -> str:
    """Plain markdown summary."""
    return f"""# {episode_title}

## Summary
{result.get('podcast_summary', 'No summary available.')}

## Guest Information
- **Name:** {result.get('podcast_guest', 'Unknown')}
- **Title:** {result.get('podcast_guest_title', 'N/A')}
- **Organization:** {result.get('podcast_guest_org', 'N/A')}

## Key Highlights
{result.get('podcast_highlights', 'No highlights available.')}

---
*Generated by PodcastGPT on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""


def generate_research_note(
    episode_title: str,
    result: Dict[str, Any],
    em_insights: Dict[str, Any],
    episode_info: Optional[Dict[str, Any]] = None,
    topic_breakdown: Optional[Dict[str, List[str]]] = None,
) -> str:
    """Professional EM research note with topic breakdown."""
    guest_name = result.get("podcast_guest", "Unknown")
    guest_title = result.get("podcast_guest_title", "")
    guest_org = result.get("podcast_guest_org", "")
    podcast_title = (
        episode_info.get("podcast_title", "Podcast") if episode_info else "Podcast"
    )

    highlights = format_highlights(result.get("podcast_highlights", ""))
    takeaways = "\n".join(
        f"{i+1}. {h.lstrip('•-* ').strip()}"
        for i, h in enumerate(highlights)
        if h.strip()
    )

    topic_section = "No structured topics extracted."
    if topic_breakdown:
        parts: List[str] = []
        for topic, points in topic_breakdown.items():
            parts.append(f"### {topic}")
            for p in points[:4]:
                clean = p[:200] + "..." if len(p) > 200 else p
                parts.append(f"- {clean}")
            parts.append("")
        topic_section = "\n".join(parts)

    bull = em_insights["bullish_score"]
    bear = em_insights["bearish_score"]
    if bull > bear:
        net = "Positive"
    elif bear > bull:
        net = "Negative"
    else:
        net = "Neutral"

    return f"""# EM Research Note: Podcast Summary
## {episode_title}

**Source:** {podcast_title}
**Date:** {datetime.now().strftime('%Y-%m-%d')}
**Analyst:** PodcastGPT AI

---

## QUICK REFERENCE

| Metric | Value |
|--------|-------|
| **Overall Sentiment** | {em_insights['sentiment']} |
| **Primary Regions** | {', '.join(em_insights['regions'])} |
| **Countries Discussed** | {', '.join(em_insights['countries']) if em_insights['countries'] else 'Broad EM'} |
| **Asset Classes** | {', '.join(em_insights['asset_classes'])} |
| **Key Themes** | {', '.join(em_insights['themes'])} |

---

## GUEST PROFILE

**{guest_name}**
{guest_title}
{guest_org}

---

## EXECUTIVE SUMMARY

{result.get('podcast_summary', 'No summary available.')}

---

## DETAILED TOPIC BREAKDOWN

{topic_section}

---

## KEY INVESTMENT THEMES

{chr(10).join(f"### {theme}" for theme in em_insights['themes'])}

---

## ACTIONABLE TAKEAWAYS

{takeaways if takeaways else 'No specific takeaways extracted.'}

---

## REGIONAL BREAKDOWN

{chr(10).join(f"- **{region}**: Discussed in this episode" for region in em_insights['regions'])}

---

## RISK CONSIDERATIONS

Based on the discussion, portfolio managers should consider:
- Sentiment indicators suggest a **{em_insights['sentiment'].lower()}** bias
- Focus areas: {', '.join(em_insights['themes'][:3])}
- Geographic exposure: {', '.join(em_insights['countries'][:5]) if em_insights['countries'] else 'Broad EM exposure'}

---

## APPENDIX: SENTIMENT ANALYSIS

- Bullish signals detected: {bull}
- Bearish signals detected: {bear}
- Net sentiment: {net}

---

*This research note was automatically generated by PodcastGPT on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
*For internal use only. Not investment advice.*
"""


def generate_quick_summary(
    episode_title: str, result: Dict[str, Any], em_insights: Dict[str, Any]
) -> str:
    """Short text summary for email/Slack."""
    highlights = format_highlights(result.get("podcast_highlights", ""))
    takeaways = "\n".join(
        f"  - {h.lstrip('•-* ').strip()}" for h in highlights[:5] if h.strip()
    )

    return f"""EM PODCAST SUMMARY: {episode_title}

SENTIMENT: {em_insights['sentiment']}
REGIONS: {', '.join(em_insights['regions'])}
THEMES: {', '.join(em_insights['themes'][:4])}

GUEST: {result.get('podcast_guest', 'Unknown')} ({result.get('podcast_guest_org', 'N/A')})

KEY POINTS:
{takeaways}

BOTTOM LINE:
{result.get('podcast_summary', 'No summary available.')[:500]}...

---
Generated by PodcastGPT | {datetime.now().strftime('%Y-%m-%d')}
"""


# ── PDF export ─────────────────────────────────────────────────────────

def _research_note_html(
    episode_title: str,
    result: Dict[str, Any],
    em_insights: Dict[str, Any],
    podcast_title: str = "",
) -> str:
    """Render a styled HTML research note suitable for PDF conversion."""
    guest = result.get("podcast_guest", "Unknown")
    guest_title = result.get("podcast_guest_title", "")
    guest_org = result.get("podcast_guest_org", "")
    summary = result.get("podcast_summary", "No summary available.")
    highlights_raw = format_highlights(result.get("podcast_highlights", ""))
    highlights_html = "\n".join(f"<li>{h.lstrip('•-* ').strip()}</li>" for h in highlights_raw if h.strip())

    regions = ", ".join(em_insights.get("regions", [])) or "Broad EM"
    countries = ", ".join(em_insights.get("countries", [])) or "Broad EM"
    themes = ", ".join(em_insights.get("themes", [])) or "—"
    asset_classes = ", ".join(em_insights.get("asset_classes", [])) or "—"
    sentiment = em_insights.get("sentiment", "—")
    bull = em_insights.get("bullish_score", 0)
    bear = em_insights.get("bearish_score", 0)
    date = datetime.now().strftime("%Y-%m-%d")

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #222; line-height: 1.6; }}
  h1 {{ color: #1a1a2e; font-size: 20px; border-bottom: 2px solid #667eea; padding-bottom: 8px; }}
  h2 {{ color: #667eea; font-size: 15px; margin-top: 24px; }}
  .meta {{ color: #666; font-size: 12px; margin-bottom: 20px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; font-size: 13px; }}
  th {{ background: #f0f2ff; color: #333; }}
  ul {{ padding-left: 20px; }}
  li {{ margin-bottom: 4px; font-size: 13px; }}
  p {{ font-size: 13px; }}
  .footer {{ margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; color: #999; font-size: 11px; }}
  .sentiment-badge {{ display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; }}
  .bull {{ background: #d4edda; color: #155724; }}
  .bear {{ background: #f8d7da; color: #721c24; }}
  .neutral {{ background: #fff3cd; color: #856404; }}
</style></head><body>
<h1>EM Research Note: {episode_title}</h1>
<div class="meta">
  <strong>Source:</strong> {podcast_title} &nbsp;|&nbsp;
  <strong>Date:</strong> {date} &nbsp;|&nbsp;
  <strong>Guest:</strong> {guest} {('— ' + guest_title) if guest_title else ''} {('@ ' + guest_org) if guest_org else ''}
</div>

<h2>Quick Reference</h2>
<table>
  <tr><th>Sentiment</th><td><span class="sentiment-badge {'bull' if 'bull' in sentiment.lower() else 'bear' if 'bear' in sentiment.lower() else 'neutral'}">{sentiment}</span></td></tr>
  <tr><th>Regions</th><td>{regions}</td></tr>
  <tr><th>Countries</th><td>{countries}</td></tr>
  <tr><th>Themes</th><td>{themes}</td></tr>
  <tr><th>Asset Classes</th><td>{asset_classes}</td></tr>
  <tr><th>Bullish Signals</th><td>{bull}</td></tr>
  <tr><th>Bearish Signals</th><td>{bear}</td></tr>
</table>

<h2>Executive Summary</h2>
<p>{summary}</p>

<h2>Key Highlights</h2>
<ul>{highlights_html}</ul>

<div class="footer">
  Generated by PodcastGPT on {date} &nbsp;|&nbsp; For internal use only. Not investment advice.
</div>
</body></html>"""


def generate_pdf_research_note(
    episode_title: str,
    result: Dict[str, Any],
    em_insights: Dict[str, Any],
    podcast_title: str = "",
) -> Optional[bytes]:
    """
    Generate a PDF research note. Returns bytes or None if weasyprint
    is unavailable. Falls back to None (caller should offer Markdown instead).
    """
    if not _WEASYPRINT_OK:
        return None
    html = _research_note_html(episode_title, result, em_insights, podcast_title)
    try:
        return WeasyprintHTML(string=html).write_pdf()
    except Exception:
        return None


def generate_html_research_note(
    episode_title: str,
    result: Dict[str, Any],
    em_insights: Dict[str, Any],
    podcast_title: str = "",
) -> str:
    """Generate a self-contained HTML research note (always works, no deps)."""
    return _research_note_html(episode_title, result, em_insights, podcast_title)
